export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RECEIVE_MESSAGE = 'You will receive a message';
export const FAILED_CHANGE_PASSWORD = 'Failed to change password';
export const USER_NOT_EXIST = "User doesn't exist";
export const INVALID_TOKEN = 'Invalid Token';
export const COMPANY_NOT_FOUND = 'Company not found';
export const APIKEY_CREATION_SUCCESS = 'Api key created successfully';
export const APIKEY_REFRESH_SUCCESS = 'Api key refreshed successfully';
